package nz.co.vista.services.wsvistawebclient_servicecontracts._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://inetviss.cineticket.com.mx:8020/vista/Proxies/DataServiceProxy_Encrypted?wsdl",
  targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
  name="DataService")
@XmlSeeAlso(
  { nz.co.vista.services.wsvistawebclient_servicecontracts._1.ObjectFactory.class, nz.co.vista.services.wsvistawebclient_datatypes._1.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface DataService
{
  @WebMethod(operationName="GetCinemaList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetCinemaList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetCinemaList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetCinemaListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetCinemaListResult", name="GetCinemaListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getCinemaList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/",
      partName="GetCinemaListRequest", name="GetCinemaListRequest")
    nz.co.vista.services.wsvistawebclient_servicecontracts._1.GetCinemaListRequest GetCinemaListRequest);

  @WebMethod(operationName="GetCinemaListAll", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetCinemaListAll")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetCinemaListAll",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetCinemaListAllResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetCinemaListAllResult", name="GetCinemaListAllResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getCinemaListAll(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/",
      partName="GetCinemaListAllRequest", name="GetCinemaListAllRequest")
    nz.co.vista.services.wsvistawebclient_servicecontracts._1.GetCinemaListAllRequest GetCinemaListAllRequest);

  @WebMethod(operationName="GetMovieList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetMovieList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetMovieList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetMovieListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetMovieListResult", name="GetMovieListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getMovieList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetMovieListRequest", name="GetMovieListRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetMovieListRequest GetMovieListRequest);

  @WebMethod(operationName="GetMovieInfoList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetMovieInfoList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetMovieInfoList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetMovieInfoListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetMovieInfoListResult", name="GetMovieInfoListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getMovieInfoList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetMovieInfoListRequest", name="GetMovieInfoListRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetMovieInfoListRequest GetMovieInfoListRequest);

  @WebMethod(operationName="GetMoviePeople", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetMoviePeople")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetMoviePeople",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetMoviePeopleResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetMoviePeopleResult", name="GetMoviePeopleResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getMoviePeople(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetMoviePeopleRequest", name="GetMoviePeopleRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetMoviePeopleRequest GetMoviePeopleRequest);

  @WebMethod(operationName="GetSessionList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetSessionList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetSessionList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetSessionListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetSessionListResult", name="GetSessionListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getSessionList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetSessionListRequest", name="GetSessionListRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetSessionListRequest GetSessionListRequest);

  @WebMethod(operationName="GetSessionInfo", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetSessionInfo")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetSessionInfo",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetSessionInfoResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetSessionInfoResult", name="GetSessionInfoResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getSessionInfo(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetSessionInfoRequest", name="GetSessionInfoRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetSessionInfoRequest GetSessionInfoRequest);

  @WebMethod(operationName="GetTicketTypeList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetTicketTypeList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetTicketTypeList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetTicketTypeListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetTicketTypeListResult", name="GetTicketTypeListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getTicketTypeList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetTicketTypeListRequest", name="GetTicketTypeListRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetTicketTypeListRequest GetTicketTypeListRequest);

  @WebMethod(operationName="GetTicketTypeFromBarcode", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetTicketTypeFromBarcode")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetTicketTypeFromBarcode",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetTicketTypeFromBarcodeResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetTicketTypeFromBarcodeResult", name="GetTicketTypeFromBarcodeResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getTicketTypeFromBarcode(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetTicketTypeFromBarcodeRequest", name="GetTicketTypeFromBarcodeRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetTicketTypeFromBarcodeRequest GetTicketTypeFromBarcodeRequest);

  @WebMethod(operationName="GetTicketTypePackage", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetTicketTypePackage")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetTicketTypePackage",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetTicketTypePackageResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetTicketTypePackageResult", name="GetTicketTypePackageResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getTicketTypePackage(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetTicketTypePackageRequest", name="GetTicketTypePackageRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetTicketTypePackageRequest GetTicketTypePackageRequest);

  @WebMethod(operationName="GetEventList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetEventList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetEventList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetEventListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetEventListResult", name="GetEventListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getEventList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetEventListRequest", name="GetEventListRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetEventListRequest GetEventListRequest);

  @WebMethod(operationName="GetEventMovieList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetEventMovieList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetEventMovieList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetEventMovieListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetEventMovieListResult", name="GetEventMovieListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getEventMovieList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetEventMovieListRequest", name="GetEventMovieListRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetEventMovieListRequest GetEventMovieListRequest);

  @WebMethod(operationName="GetShowtimeDateList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetShowtimeDateList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetShowtimeDateList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetShowtimeDateListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetShowtimeDateListResult", name="GetShowtimeDateListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getShowtimeDateList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetShowtimeDateListRequest", name="GetShowtimeDateListRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetShowtimeDateListRequest GetShowtimeDateListRequest);

  @WebMethod(operationName="GetCinemaOpForSession", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetCinemaOpForSession")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetCinemaOpForSession",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetCinemaOpForSessionResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetCinemaOpForSessionResult", name="GetCinemaOpForSessionResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getCinemaOpForSession(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/",
      partName="GetCinemaOpForSessionRequest", name="GetCinemaOpForSessionRequest")
    nz.co.vista.services.wsvistawebclient_servicecontracts._1.GetCinemaOpForSessionRequest GetCinemaOpForSessionRequest);

  @WebMethod(operationName="GetPrintStream", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetPrintStream")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetPrintStream",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetPrintStreamResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetPrintStreamResult", name="GetPrintStreamResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getPrintStream(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
      partName="GetPrintStreamRequest", name="GetPrintStreamRequest")
    nz.co.vista.services.wsvistawebclient_servicecontracts._1.GetPrintStreamRequest GetPrintStreamRequest);

  @WebMethod(operationName="GetConfirmationDetails", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetConfirmationDetails")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetConfirmationDetails",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetConfirmationDetailsResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetConfirmationDetailsResult", name="GetConfirmationDetailsResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getConfirmationDetails(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetConfirmationDetailsRequest", name="GetConfirmationDetailsRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetConfirmationDetailsRequest GetConfirmationDetailsRequest);

  @WebMethod(operationName="GetConcessionItemsList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetConcessionItemsList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetConcessionItemsList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetConcessionItemsListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetConcessionItemsListResult", name="GetConcessionItemsListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getConcessionItemsList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetConcessionItemsListRequest", name="GetConcessionItemsListRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetConcessionItemsListRequest GetConcessionItemsListRequest);

  @WebMethod(operationName="GetMovieShowtimes", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetMovieShowtimes")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetMovieShowtimes",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetMovieShowtimesResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetMovieShowtimesResult", name="GetMovieShowtimesResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getMovieShowtimes(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetMovieShowtimesRequest", name="GetMovieShowtimesRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetMovieShowtimesRequest GetMovieShowtimesRequest);

  @WebMethod(operationName="GetProductInfo", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetProductInfo")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetProductInfo",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetProductInfoResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetProductInfoResult", name="GetProductInfoResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getProductInfo(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetProductInfoRequest", name="GetProductInfoRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetProductInfoRequest GetProductInfoRequest);

  @WebMethod(operationName="GetClientList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetClientList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetClientList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetClientListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetClientListResult", name="GetClientListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getClientList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetClientListRequest", name="GetClientListRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetClientListRequest GetClientListRequest);

  @WebMethod(operationName="GiftCardBalanceRequest", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GiftCardBalanceRequest")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GiftCardBalanceRequest",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GiftCardBalanceRequestResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GiftCardBalanceRequestResult", name="GiftCardBalanceRequestResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse giftCardBalanceRequest(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GCBalanceRequest", name="GCBalanceRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GiftCardBalanceRequest GCBalanceRequest);

  @WebMethod(operationName="CreateClient", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/CreateClient")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/CreateClient",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/CreateClientResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
    partName="CreateClientResult", name="CreateClientResult")
  public nz.co.vista.services.wsvistawebclient_servicecontracts._1.Response createClient(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="CreateClientRequest", name="CreateClientRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.CreateClientRequest CreateClientRequest);

  @WebMethod(operationName="UpdateClient", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/UpdateClient")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/UpdateClient",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/UpdateClientResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
    partName="UpdateClientResult", name="UpdateClientResult")
  public nz.co.vista.services.wsvistawebclient_servicecontracts._1.Response updateClient(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="UpdateClientRequest", name="UpdateClientRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.UpdateClientRequest UpdateClientRequest);

  @WebMethod(operationName="GetLtyMembershipConcessionItem", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetLtyMembershipConcessionItem")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetLtyMembershipConcessionItem",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetLtyMembershipConcessionItemResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetLtyMembershipConcessionItemResult", name="GetLtyMembershipConcessionItemResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getLtyMembershipConcessionItem(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
      partName="GetLtyMembershipConcessionItemRequest", name="GetLtyMembershipConcessionItemRequest")
    nz.co.vista.services.wsvistawebclient_servicecontracts._1.GetLtyMembershipConcessionItemRequest GetLtyMembershipConcessionItemRequest);

  @WebMethod(operationName="GetConfigSettingList", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetConfigSettingList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetConfigSettingList",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetConfigSettingListResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
    partName="GetConfigSettingListResult", name="GetConfigSettingListResult")
  public nz.co.vista.services.wsvistawebclient_datatypes._1.DataResponse getConfigSettingList(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
      partName="GetConfigSettingListRequest", name="GetConfigSettingListRequest")
    nz.co.vista.services.wsvistawebclient_servicecontracts._1.GetConfigSettingListRequest GetConfigSettingListRequest);

  @WebMethod(operationName="GetOrderHistory", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetOrderHistory")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetOrderHistory",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetOrderHistoryResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
    partName="GetOrderHistoryResult", name="GetOrderHistoryResult")
  public nz.co.vista.services.wsvistawebclient_servicecontracts._1.GetOrderHistoryResponse getOrderHistory(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
      partName="GetOrderHistoryRequest", name="GetOrderHistoryRequest")
    nz.co.vista.services.wsvistawebclient_servicecontracts._1.GetOrderHistoryRequest GetOrderHistoryRequest);

  @WebMethod(operationName="GetCinemaSiteGroups", action="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetCinemaSiteGroups")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/GetCinemaSiteGroups",
    output="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1/DataService/GetCinemaSiteGroupsResponse")
  @WebResult(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
    partName="GetCinemaSiteGroupsResult", name="GetCinemaSiteGroupsResult")
  public nz.co.vista.services.wsvistawebclient_servicecontracts._1.GetCinemaSiteGroupsResponse getCinemaSiteGroups(@WebParam(targetNamespace="http://vista.co.nz/services/WSVistaWebClient.DataTypes/1/",
      partName="GetCinemaSiteGroupsRequest", name="GetCinemaSiteGroupsRequest")
    nz.co.vista.services.wsvistawebclient_datatypes._1.GetCinemaSiteGroupsRequest GetCinemaSiteGroupsRequest);
}
