package nz.co.vista.services.wsvistawebclient_servicecontracts._1;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@SuppressWarnings("deprecation")
@WebServiceClient(wsdlLocation = "http://inetviss.cineticket.com.mx:8020/vista/Proxies/DataServiceProxy_Encrypted?wsdl", targetNamespace = "http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1", name = "DataService")
public class DataService_Service extends Service {
	private static URL wsdlLocationURL;

	private static Logger logger;
	static {
		try {
			logger = Logger
					.getLogger("nz.co.vista.services.wsvistawebclient_servicecontracts._1.DataService_Service");
			URL baseUrl = DataService_Service.class.getResource(".");
			if (baseUrl == null) {
				wsdlLocationURL = DataService_Service.class
						.getResource("http://inetviss.cineticket.com.mx:8020/vista/Proxies/DataServiceProxy_Encrypted?wsdl");
				if (wsdlLocationURL == null) {
					baseUrl = new File(".").toURL();
					wsdlLocationURL = new URL(
							baseUrl,
							"http://inetviss.cineticket.com.mx:8020/vista/Proxies/DataServiceProxy_Encrypted?wsdl");
				}
			} else {
				if (!baseUrl.getPath().endsWith("/")) {
					baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
				}
				wsdlLocationURL = new URL(
						baseUrl,
						"http://inetviss.cineticket.com.mx:8020/vista/Proxies/DataServiceProxy_Encrypted?wsdl");
			}
		} catch (MalformedURLException e) {
			logger.log(
					Level.ALL,
					"Failed to create wsdlLocationURL using http://inetviss.cineticket.com.mx:8020/vista/Proxies/DataServiceProxy_Encrypted?wsdl",
					e);
		}
	}

	public DataService_Service() {
		super(
				wsdlLocationURL,
				new QName(
						"http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
						"DataService"));
	}

	public DataService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	@WebEndpoint(name = "DataService")
	public nz.co.vista.services.wsvistawebclient_servicecontracts._1.DataService getDataService() {
		return (nz.co.vista.services.wsvistawebclient_servicecontracts._1.DataService) super
				.getPort(
						new QName(
								"http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
								"DataService"),
						nz.co.vista.services.wsvistawebclient_servicecontracts._1.DataService.class);
	}

	@WebEndpoint(name = "DataService")
	public nz.co.vista.services.wsvistawebclient_servicecontracts._1.DataService getDataService(
			WebServiceFeature... features) {
		return (nz.co.vista.services.wsvistawebclient_servicecontracts._1.DataService) super
				.getPort(
						new QName(
								"http://vista.co.nz/services/WSVistaWebClient.ServiceContracts/1",
								"DataService"),
						nz.co.vista.services.wsvistawebclient_servicecontracts._1.DataService.class,
						features);
	}
}
