package mobi.allshoppings.bz.spi.fields;

import java.util.Arrays;


public class BrandBzFields extends BzFields {

	protected BrandBzFields() {
		INTERNAL_ALWAYS_FIELDS.addAll(Arrays.asList(
				"identifier"
				));
		INTERNAL_DEFAULT_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"areaId",
				"email",
				"favorite"
				));
		INTERNAL_INVALID_FIELDS.addAll(Arrays.asList(
				"key",
				"invoicingInfo*"
				));
		INTERNAL_READONLY_FIELDS.addAll(Arrays.asList(
				"identifier",
				"key",
				"invoicingInfo*"
				));
		INTERNAL_LEVEL_LIST_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"favorite",
				"creationDateTime",
				"lastUpdate"
				));
		INTERNAL_LEVEL_ALL_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"shoppingAvatarId",
				"photoId",
				"videoId",
				"areaId",
				"creationDateTime",
				"statusModificationDateTime",
				"description",
				"contactInfo.mail",
				"contactInfo.phone",
				"contactInfo.twitterId",
				"contactInfo.webURL",
				"contactInfo.youtubeChannel",
				"contactInfo.facebookId",
				"contactInfo.googleId",
				"contactInfo.foursquareId",
				"contactInfo.tiendeoId",
				"favoriteCount",
				"checkinCount",
				"points",
				"favorite"
				));
		INTERNAL_INDEXING_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"areaId",
				"country",
				"description"
				));
		INTERNAL_LEVEL_FAST_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"email",
				"areaId",
				"avatarId",
				"favorite"
				));
		INTERNAL_LEVEL_PUBLIC_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"photoId",
				"videoId",
				"areaId",
				"creationDateTime",
				"statusModificationDateTime",
				"description",
				"contactInfo.mail",
				"contactInfo.phone",
				"contactInfo.twitterId",
				"contactInfo.webURL",
				"contactInfo.youtubeChannel",
				"contactInfo.facebookId",
				"contactInfo.foursquareId",
				"contactInfo.tiendeoId",
				"contactInfo.googleId",
				"favorite"
				));
	}
}