package mobi.allshoppings.bz.spi.fields;

import java.util.Arrays;


public class FloorMapBzFields extends BzFields {

	protected FloorMapBzFields() {
		INTERNAL_ALWAYS_FIELDS.addAll(Arrays.asList(
				"identifier"
				));
		INTERNAL_DEFAULT_FIELDS.addAll(Arrays.asList(
				"identifier"
				));
		INTERNAL_INVALID_FIELDS.addAll(Arrays.asList(
				"key"
				));
		INTERNAL_READONLY_FIELDS.addAll(Arrays.asList(
				"identifier",
				"key"
				));
		INTERNAL_LEVEL_LIST_FIELDS.addAll(Arrays.asList(
				"identifier",
				"shoppingId",
				"shoppingName",
				"floor",
				"imageId",
				"status",
				"creationDateTime",
				"lastUpdate",
				"marginTop",
				"screenHeight",
				"screenWidth",
				"corrected",
				"mapHeight",
				"mapWidth"
				));
		INTERNAL_LEVEL_ALL_FIELDS.addAll(Arrays.asList(
				"identifier",
				"shoppingId",
				"shoppingName",
				"floor",
				"imageId",
				"status",
				"creationDateTime",
				"lastUpdate",
				"marginTop",
				"screenHeight",
				"screenWidth",
				"corrected",
				"mapHeight",
				"mapWidth"
				));
		INTERNAL_INDEXING_FIELDS.addAll(Arrays.asList(
				"identifier",
				"shoppingId",
				"shoppingName",
				"floor",
				"imageId",
				"status",
				"creationDateTime",
				"lastUpdate",
				"marginTop",
				"screenHeight",
				"screenWidth",
				"corrected",
				"mapHeight",
				"mapWidth"
				));
		INTERNAL_LEVEL_FAST_FIELDS.addAll(Arrays.asList(
				"identifier",
				"shoppingId",
				"shoppingName",
				"floor",
				"imageId",
				"status",
				"creationDateTime",
				"lastUpdate",
				"marginTop",
				"screenHeight",
				"screenWidth",
				"corrected",
				"mapHeight",
				"mapWidth"
				));
		INTERNAL_LEVEL_PUBLIC_FIELDS.addAll(Arrays.asList(
				"identifier",
				"shoppingId",
				"shoppingName",
				"floor",
				"imageId",
				"status",
				"creationDateTime",
				"lastUpdate",
				"marginTop",
				"screenHeight",
				"screenWidth",
				"corrected",
				"mapHeight",
				"mapWidth"
				));
	}
}