package mobi.allshoppings.bz.spi.fields;

import java.util.Arrays;

public class OfferBzFields extends BzFields {

	protected OfferBzFields() {
		INTERNAL_ALWAYS_FIELDS.addAll(Arrays.asList(
				"identifier"
				));
		INTERNAL_DEFAULT_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"shoppingId",
				"shoppingName",
				"brandId",
				"brandName",
				"storeId",
				"storeName",
				"offerTypeId",
				"offerTypeName",
				"exclusive",
				"description",
				"validFrom",
				"validTo",
				"favorite"
				));
		INTERNAL_INVALID_FIELDS.addAll(Arrays.asList(
				"key"
				));
		INTERNAL_READONLY_FIELDS.addAll(Arrays.asList(
				"identifier",
				"key"
				));
		INTERNAL_LEVEL_LIST_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"shoppingId",
				"shoppingName",
				"brandId",
				"brandName",
				"storeId",
				"storeName",
				"offerTypeId",
				"offerTypeName",
				"exclusive",
				"description",
				"validFrom",
				"validTo",
				"favorite",
				"creationDateTime",
				"lastUpdate"
				));
		INTERNAL_LEVEL_ALL_FIELDS.addAll(Arrays.asList(
				"identifier",
				"shoppings",
				"brands",
				"stores",
				"offerTypeId",
				"offerTypeName",
				"offerTypeRibbonText",
				"areaId",
				"name",
				"description",
				"avatarId",
				"photoId",
				"videoId",
				"creationDateTime",
				"statusModificationDateTime",
				"policies",
				"validFrom",
				"validTo",
				"lastUpdate",
				"availableFinancialEntities",
				"notifyFromHour",
				"notifyToHour",
				"notifyDays",
				"country",
				"source",
				"origin",
				"exclusive",
				"acl",
				"expired",
				"shoppingList",
				"brandList",
				"storeList",
				"financialEntityList",
				"points"
				));
		INTERNAL_INDEXING_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"areas",
				"shoppings",
				"availableFinancialEntities",
				"country",
				"brands",
				"stores",
				"areaId",
				"description",
				"offerTypeName",
				"offerTypeRibbonText"
				));
		INTERNAL_LEVEL_FAST_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"shoppingId",
				"shoppingName",
				"brandId",
				"brandName",
				"storeId",
				"storeName",
				"offerTypeId",
				"offerTypeName",
				"exclusive",
				"description",
				"validFrom",
				"validTo",
				"favorite"
				));
		INTERNAL_LEVEL_PUBLIC_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"shoppingId",
				"shoppingName",
				"brandId",
				"brandName",
				"storeId",
				"storeName",
				"areas",
				"exclusive",
				"description",
				"photoId",
				"videoId",
				"creationDateTime",
				"statusModificationDateTime",
				"offerTypeId",
				"offerTypeName",
				"policies",
				"validFrom",
				"validTo",
				"favorite"
				));
	}
}
