package mobi.allshoppings.bz.spi.fields;

import java.util.Arrays;


public class ShoppingBzFields extends BzFields {

	protected ShoppingBzFields() {
		INTERNAL_ALWAYS_FIELDS.addAll(Arrays.asList(
				"identifier"
				));
		INTERNAL_DEFAULT_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"email",
				"favorite"
				));
		INTERNAL_INVALID_FIELDS.addAll(Arrays.asList(
				"key",
				"invoicingInfo*"
				));
		INTERNAL_READONLY_FIELDS.addAll(Arrays.asList(
				"identifier",
				"key",
				"invoicingInfo*"
				));
		INTERNAL_LEVEL_LIST_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"address.city",
				"address.country",
				"address.latitude",
				"address.longitude",
				"address.province",
				"avatarId",
				"favorite",
				"creationDateTime",
				"lastUpdate"
				));
		INTERNAL_LEVEL_ALL_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"brandAvatarId",
				"photoId",
				"videoId",
				"serviceId",
				"creationDateTime",
				"statusModificationDateTime",
				"description",
				"address.city",
				"address.country",
				"address.latitude",
				"address.longitude",
				"address.neighborhood",
				"address.province",
				"address.streetName",
				"address.streetNumber",
				"address.zipCode",
				"contactInfo.mail",
				"contactInfo.phone",
				"contactInfo.twitterId",
				"contactInfo.webURL",
				"contactInfo.youtubeChannel",
				"contactInfo.facebookId",
				"contactInfo.googleId",
				"contactInfo.foursquareId",
				"structureInfo.brandCount",
				"structureInfo.floorCount",
				"structureInfo.storeCount",
				"fenceSize",
				"checkinAreaSize",
				"favoriteCount",
				"checkinCount",
				"points",
				"favorite"
				));
		INTERNAL_INDEXING_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"description",
				"serviceId",
				"address.city",
				"address.country",
				"address.neighborhood",
				"address.province",
				"address.streetName"
				));
		INTERNAL_LEVEL_FAST_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"email",
				"avatarId",
				"favorite"
				));
		INTERNAL_LEVEL_PUBLIC_FIELDS.addAll(Arrays.asList(
				"identifier",
				"name",
				"avatarId",
				"photoId",
				"videoId",
				"serviceId",
				"creationDateTime",
				"statusModificationDateTime",
				"description",
				"address.city",
				"address.country",
				"address.latitude",
				"address.longitude",
				"address.neighborhood",
				"address.province",
				"address.streetName",
				"address.streetNumber",
				"address.zipCode",
				"contactInfo.mail",
				"contactInfo.phone",
				"contactInfo.twitterId",
				"contactInfo.webURL",
				"contactInfo.youtubeChannel",
				"contactInfo.facebookId",
				"contactInfo.googleId",
				"structureInfo.brandCount",
				"structureInfo.floorCount",
				"structureInfo.storeCount",
				"contactInfo.foursquareId",
				"fenceSize",
				"checkinAreaSize",
				"favoriteCount",
				"checkinCount",
				"favorite"
				));
	}
}